server:
  host: "0.0.0.0"
  port: 8080

streams:
  - id: "rtsp0"
    type: "rtsp"

    rtsp:
      url: "rtsp://rtspstream:iC_SMRxQh3s8d66xv1LBW@zephyr.rtsp.stream/movie"
      tcp: true
      fps: 25
      latency_ms: 1000

    outputs:
      profiles:
        inference:
          width: 960
          height: 540
          fps: 10
          format: "BGR"
        ui:
          width: 1280
          height: 720
          fps: 10
          jpeg_quality: 75

    replicate:
      count: 2

  - id: "file0"
    type: "file"

    file:
      path: "../../../assets/test.mp4"
      fps: 10

    outputs:
      profiles:
        inference:
          width: 960
          height: 540
          fps: 10
          format: "BGR"
        ui:
          width: 1280
          height: 720
          fps: 10
          jpeg_quality: 75

    replicate:
      count: 2