server:
  host: "0.0.0.0"
  port: 8080

streams:
  - id: "file0"
    type: "file"

    file:
      path: "../../../assets/test.mp4"
      fps: 10

    outputs:
      fps: 10
      profiles:
        inference:
          width: 640
          height: 640
          keep_aspect: true
          interp: "linear"
          format: "BGR"
        ui:
          width: 1280
          height: 720
          keep_aspect: true
          interp: "linear"
          jpeg_quality: 75

    replicate:
      count: 2
