server:
  host: "0.0.0.0"
  port: 8080

streams:
  - id: "rtsp0"
    type: "rtsp"

    rtsp:
      url: "rtsp://rtspstream:iC_SMRxQh3s8d66xv1LBW@zephyr.rtsp.stream/pattern"
      tcp: true
      fps: 30
      latency_ms: 1000

    outputs:
      fps: 30
      profiles:
        inference:
          width: 640
          height: 640
          keep_aspect: true
          interp: "linear"
          format: "BGR"
        ui:
          width: 1280
          height: 720
          keep_aspect: true
          interp: "linear"
          jpeg_quality: 75

    replicate:
      count: 2
