server:
  host: "0.0.0.0"
  port: 8080

streams:
  - id: "cam0"
    type: "webcam"

    webcam:
      device: "/dev/video0"
      width: 1280
      height: 720
      fps: 15
      mjpg: true

    outputs:
      fps: 15
      profiles:
        inference:
          width: 640
          height: 640
          keep_aspect: true
          interp: "linear"
          format: "BGR"
        ui:
          width: 1280
          height: 720
          keep_aspect: true
          interp: "linear"
          jpeg_quality: 75

    replicate:
      count: 1
